use_frameworks!

platform :ios, '8.0'

target 'WBDownload_Example' do
  pod 'WBDownload', :path => '../'

  target 'WBDownload_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
